### PR TITLE
[wip] try to upgrade all deps

### PR DESCRIPTION
**Pull request by dimaqq**
Mostly works...

Fails the loader test, somehow the `require`'s `.mo` file is `undefined` :(

```js
… ~/gettext.js> yarn test
yarn run v1.21.1
$ jest
 PASS  tests/utils.test.js
 PASS  tests/parser.test.js
 PASS  tests/runtime.test.js
 FAIL  tests/loader.test.js
  ● Compiles en.mo file to js module

    expect(received).toBe(expected) // Object.is equality

    Expected: "import gettext from 'gettextjs';
    import Immutable from 'immutable';·
    const headers = Immutable.fromJS({\"project-id-version\":\"gettextjs\",\"po-revision-date\":\"2015-10-26 09\",\"last-translator\":\"Jonas Obrist <ojiidotch@gmail.com>\",\"language\":\"en\",\"mime-version\":\"1.0\",\"content-type\":\"text/plain; charset=UTF-8\",\"content-transfer-encoding\":\"8bit\",\"plural-forms\":\"nplurals=2; plural=(n != 1);\"});
    const messages = Immutable.fromJS({\"\":[\"Project-Id-Version: gettextjs\\nPO-Revision-Date: 2015-10-26 09:11+0000\\nLast-Translator: Jonas Obrist <ojiidotch@gmail.com>\\nLanguage: en\\nMIME-Version: 1.0\\nContent-Type: text/plain; charset=UTF-8\\nContent-Transfer-Encoding: 8bit\\nPlural-Forms: nplurals=2; plural=(n != 1);\\n\"],\"simple-string\":[\"A simple string\"],\"singular-string\":[\"Singular form!\",\"Plural form!\"]});
    const plural = n => ((n != 1)) * 1;·
    export default new gettext.Translations(headers, messages, plural);"
    Received: undefined

      39 |   const stats = await compiler('en.mo');
      40 |   const output = stats.toJson().modules[0].source;
    > 41 |   expect(output).toBe(`import gettext from 'gettextjs';
         |                  ^
      42 | import Immutable from 'immutable';
      43 |
      44 | const headers = Immutable.fromJS({"project-id-version":"gettextjs","po-revision-date":"2015-10-26 09","last-translator":"Jonas Obrist <ojiidotch@gmail.com>","language":"en","mime-version":"1.0","content-type":"text/plain; charset=UTF-8","content-transfer-encoding":"8bit","plural-forms":"nplurals=2; plural=(n != 1);"});

      at _callee$ (tests/loader.test.js:41:18)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● Compiles ja.mo file to js module

    expect(received).toBe(expected) // Object.is equality

    Expected: "import gettext from 'gettextjs';
    import Immutable from 'immutable';·
    const headers = Immutable.fromJS({\"project-id-version\":\"gettextjs\",\"po-revision-date\":\"2015-10-26 09\",\"last-translator\":\"Jonas Obrist <ojiidotch@gmail.com>\",\"language\":\"ja\",\"mime-version\":\"1.0\",\"content-type\":\"text/plain; charset=UTF-8\",\"content-transfer-encoding\":\"8bit\",\"plural-forms\":\"nplurals=1; plural=0;\"});
    const messages = Immutable.fromJS({\"\":[\"Project-Id-Version: gettextjs\\nPO-Revision-Date: 2015-10-26 09:11+0000\\nLast-Translator: Jonas Obrist <ojiidotch@gmail.com>\\nLanguage: ja\\nMIME-Version: 1.0\\nContent-Type: text/plain; charset=UTF-8\\nContent-Transfer-Encoding: 8bit\\nPlural-Forms: nplurals=1; plural=0;\\n\"],\"simple-string\":[\"簡単なストリング\"],\"singular-string\":[\"日本語には複数形がありません。\"]});
    const plural = n => (0) * 1;·
    export default new gettext.Translations(headers, messages, plural);"
    Received: undefined

      52 |   const stats = await compiler('ja.mo');
      53 |   const output = stats.toJson().modules[0].source;
    > 54 |   expect(output).toBe(`import gettext from 'gettextjs';
         |                  ^
      55 | import Immutable from 'immutable';
      56 |
      57 | const headers = Immutable.fromJS({"project-id-version":"gettextjs","po-revision-date":"2015-10-26 09","last-translator":"Jonas Obrist <ojiidotch@gmail.com>","language":"ja","mime-version":"1.0","content-type":"text/plain; charset=UTF-8","content-transfer-encoding":"8bit","plural-forms":"nplurals=1; plural=0;"});

      at _callee2$ (tests/loader.test.js:54:18)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● Compiled file actually works

    TypeError: Cannot read property 'gettext' of undefined

      74 |         fs.writeFileSync(module, output);
      75 |         const locale = require(module).default;
    > 76 |         expect(locale.gettext('simple-string')).toEqual('A simple string');
         |                       ^
      77 |         resolve();
      78 |       });
      79 |     } catch(err) {

      at tests/loader.test.js:76:23
      at _dirCreated (node_modules/tmp/lib/tmp.js:333:7)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       3 failed, 14 passed, 17 total
Snapshots:   0 total
Time:        3.133s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
… ~/gettext.js>
```

### CODE REVIEW

**Comment by dimaqq** [comment]
I'm quite confused at this point... your esteemed wisdom is thought after, @ojii

**Comment by ojii** [comment]
loader tests seem fubar https://github.com/ojii/gettext.js/tree/dimaqq-try-upgrade-deps

**Comment by ojii** [comment]
loader tests seem fubar https://github.com/ojii/gettext.js/tree/dimaqq-try-upgrade-deps, somehow webpack fails to find the `gettextjs` library itself but in older versions that worked.

**Comment by dimaqq** [comment]
yay, I fixed webpack wrt. being able to find (local) gettextjs.

so, now, it finds runtime.js but cannot parse it 😅

the next step I need to do is to teach webpack or babel to strip flow annotations.

**Comment by dimaqq** [comment]
Current state:

```
    >  97 |   expect(stats.toJson().errors).toBe([]);
          |                                 ^
       98 |   return new Promise((resolve, reject) => {
       99 |     try {
      100 |       tmp.dir((err, path) => {

      at _callee3$ (tests/loader.test.js:97:33)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by dimaqq** [comment]
More details:
```
    Details:

    /private/var/folders/mb/zbl55f151xgcgcvqd27zdp1c0000gn/T/tmp-518203CNwMOVZtzEt/bundle.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _typeof2 from "@babel/runtime/helpers/typeof";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

So, it seems that `mo→js` path produces something, or possibly babel mangles it to something that's a mix of old-school module and es6 module? 🤔

I wonder if it's easier to convert mo to json and use native json loader after that 🤔

**Comment by dimaqq** [comment]
Entirety of the generated `bundle.js` source:
```js
    import _typeof2 from "@babel/runtime/helpers/typeof";

    function _typeof(obj) {
      if (typeof Symbol === "function" && _typeof2(Symbol.iterator) === "symbol") {
        module.exports = _typeof = function _typeof(obj) {
          return _typeof2(obj);
        };
      } else {
        module.exports = _typeof = function _typeof(obj) {
          return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : _typeof2(obj);
        };
      }

      return _typeof(obj);
    }

    module.exports = _typeof;
```

It's missing the translations 🔥 
It's uses es6 style imports and cjs exports 🤷‍♂

**Comment by dimaqq** [comment]
ultimately there are 5 modules in `output`
* 4 helpers (typeof, classCallCheck, defineProperties, module loader polyfill?)
* 1 `undefined` 😢

**Comment by dimaqq** [comment]
I bet this is stale now, feel free to close @ojii

**Pull request closed without merging**
